"use client";

import { RecommendationsList } from '@/components/RecommendationsList';
import { Button } from '@/components/ui/button';
import { ArrowLeft, Lightbulb } from 'lucide-react';
import Link from 'next/link';

export default function RecommendationsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white">
      <div className="mx-auto max-w-4xl px-4 py-6">
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <Link href="/">
              <Button variant="ghost" size="sm">
                <ArrowLeft className="w-4 h-4 mr-2" />
                Back
              </Button>
            </Link>
            <div className="flex items-center gap-2">
              <Lightbulb className="w-6 h-6 text-blue-600" />
              <h1 className="text-2xl font-bold text-gray-900">AI Advice History</h1>
            </div>
          </div>
        </div>

        {/* Recommendations */}
        <div className="space-y-6">
          <div className="text-center mb-8">
            <p className="text-gray-600 max-w-2xl mx-auto">
              View AI productivity advice you've received in the past.
              These recommendations are generated by analyzing your work patterns.
            </p>
          </div>
          
          <RecommendationsList limit={20} showHeader={false} />
        </div>
      </div>
    </div>
  );
}
